# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  core:build:
    desc: Build the Go application
    cmds:
      - go build ./apps/core/cmd

  core:up:
    aliases: [core:start, core:run]
    desc: Start the application with Docker Compose and run the Go application
    preconditions:
      - sh: docker info
        msg: "Docker daemon is not running. Please start Docker."
    cmds:
      - docker-compose up -d
      - go run ./apps/core/cmd
