// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repo

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	GetUserByID(ctx context.Context, id pgtype.UUID) (GetUserByIDRow, error)
	RegisterUser(ctx context.Context, arg RegisterUserParams) (RegisterUserRow, error)
}

var _ Querier = (*Queries)(nil)
